name: Java Application Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'
        architecture: x64

    - name: Compile Java code and create JAR
      run: |
         # Compile your Java code
         javac HelloWorld.java
         # Create a JAR file
         jar cfe HelloWorld.jar HelloWorld HelloWorld.class

    - name: Save JAR as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: HelloWorld-JAR
        path: HelloWorld.jar

    - name: Create ZIP file
      run: zip HelloWorld.zip HelloWorld.jar

    - name: Save ZIP as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: HelloWorld-ZIP
        path: HelloWorld.zip

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1



    - name: Upload ZIP to S3
      run: aws s3 cp HelloWorld.zip s3://pocdemo/

    - name: Trigger Lambda Function
      run: aws lambda invoke --function-name pocfunc --payload '{}' output.json

    - name: Show Lambda Output
      run: cat output.json
